{% set name = "cylinter" %}
{% set version = "0.0.52" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/cylinter.git
  git_tag: v0.0.52

build:
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cylinter=cylinter.cylinter:main
  noarch: python
channels:
  - conda-forge
requirements:
  build:
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - cellcutter
    - hdbscan
    - joblib
    - magicgui
    - matplotlib
    - napari
    - numpy
    - natsort
    - numba
    - pandas
    - pyarrow
    - pyqt==5.15.11  # ensuring PyQT5
    - ffmpeg
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - seaborn
    - tifffile
    - umap-learn
    - zarr <3
    - numcodecs <0.12  # ensuring compatibility with Zarr2
    - svglib
    - pypdf2
    - imagecodecs  # MIBI data fails to be read without this
    - opencv==4.8.*  # ensuring PyQT5 build

test:
  imports:
    - cylinter

about:
  home: https://labsyspharm.github.io/cylinter/
  license: MIT
  license_family: BSD
  summary: Quality Control Software for Multiplex Microscopy
